name: tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag nepolin/calculator-trs:latest --tag nepolin/calculator-trs:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run nepolin/calculator-trs:latest make check
    - name: Corre pruebas y evalua cobertura
      run: docker run nepolin/calculator-trs:latest make tests
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push nepolin/calculator-trs:latest
    - name: Sube sha a Docker Hub
      run: docker push nepolin/calculator-trs:${GITHUB_SHA:0:4}
